[package]
name = "gdtf_parser"
version = "0.1.0"
authors = ["michaelhugi <michael.hugi@informaticon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.22"
zip = "0.5"